CREATE TABLE `m_order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `title` varchar(100) NOT NULL,
  `amount_jp` decimal(10,3) NOT NULL DEFAULT '0.000',
  `amount_cn` decimal(10,3) NOT NULL DEFAULT '0.000',
  `fee` decimal(10,3) NOT NULL DEFAULT '0.000',
  `shipping_fee` decimal(10,3) NOT NULL DEFAULT '0.000',
  `total` decimal(10,3) NOT NULL DEFAULT '0.000',
  `shipping_method` int(1) NOT NULL DEFAULT '0',
  `status` int(1) NOT NULL DEFAULT '0',
  `shopper_id` int(11) DEFAULT NULL,
  `pay_link` varchar(255) DEFAULT NULL,
  `pay_no` varchar(45) DEFAULT NULL,
  `tracking_code` varchar(45) DEFAULT NULL,
  `create_date` timestamp NULL DEFAULT NULL,
  `order_date` timestamp NULL DEFAULT NULL,
  `pay_date` timestamp NULL DEFAULT NULL,
  `send_date` timestamp NULL DEFAULT NULL,
  `receive_date` timestamp NULL DEFAULT NULL,
  `cancel_date` timestamp NULL DEFAULT NULL,
  `upd_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flg` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
