-- 无法呈现对象 APPLICATION 的 TABLE DDL。带有 DBMS_METADATA 的 M_ARTICLE_COMMENT 正在尝试内部生成器。
CREATE TABLE M_ARTICLE_COMMENT 
(
  COMMENT_ID VARCHAR2(15 BYTE) NOT NULL 
, SENDER_USER_ID VARCHAR2(15 BYTE) 
, PARENT_ID VARCHAR2(15 BYTE) 
, ARTICLE_ID VARCHAR2(15 BYTE) 
, ADD_DATE DATE 
, UPD_DATE DATE 
, DEL_FLG CHAR(1 BYTE) DEFAULT 0 
, CONTENT NCLOB 
, CONSTRAINT M_COMMENT_PK PRIMARY KEY 
  (
    COMMENT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX M_COMMENT_PK ON M_ARTICLE_COMMENT (COMMENT_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
LOB (CONTENT) STORE AS SYS_LOB0000036851C00008$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE USERS 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
)
