--------------------------------------------------------
--  DDL for Table M_CIRCLE
--------------------------------------------------------

  CREATE TABLE "APPLICATION"."M_CIRCLE" 
   (	"CIRCLE_ID" VARCHAR2(15 BYTE), 
	"NAME" NVARCHAR2(50), 
	"LINK" VARCHAR2(255 BYTE), 
	"PENNAME" NVARCHAR2(50), 
	"ADD_DATE" DATE DEFAULT SYSDATE, 
	"UPD_DATE" DATE DEFAULT SYSDATE, 
	"DEL_FLG" CHAR(1 BYTE) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
